from typing import TypedDict, List
from langchain_core.documents import Document


# state for the agent
class RAGState(TypedDict):
    query: str
    retrieved_docs: List[Document]  # from vector db
    reranked_docs: List[Document]
    response: dict
    route: str  # "VECTOR_DB or RDBMS"
    generated_sql: str  # SQL generated by nl2sql
    sql_result: str  # output of raw sql execution result
